---
- name: Install Mongodb
  hosts: sshproxy
  become: True
  become_method: sudo
  tasks:
# tasks file for mongodb
  - name: Copy mongodb repo for yum
    copy:
      src: mongodb-org.repo
      dest: /etc/yum.repos.d/mongodb-org.repo
  - name: Install repo for yum
    yum:
      name: mongodb-org
      state: present
  - name: modification du fichier conf pour accces exterieur
    lineinfile:
      path: /etc/mongod.conf
      regexp: '^  bindIp'
      line: "  bindIp: 0.0.0.0"


  - name: Start service mongod, if not started
    service:
      name: mongod
      state: started

  - name: install epel-release
    yum:
      name: epel-release
      state: present

  - name: install python-pip
    yum:
      name: python-pip
      state: present

  - name: install pymongo
    pip:
      name: pymongo

  - name: create mongodb user
    mongodb_user:
      database: "admin"
      name: "myUserAdmin"
      password: "abc123"
      roles: userAdminAnyDatabase
      state: present

  - name: fill the database
    shell: mongo admin -u myUserAdmin -p abc123 --eval 'db.customer.insert({firstName:"Paul",lastName:"Chirac"})'
  - name: fill the database
    shell: mongo admin -u myUserAdmin -p abc123 --eval 'db.customer.insert({firstName:"Henry",lastName:"Quatre"})'

  
